# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [42]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [43]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [44]:
sinasc_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27028 entries, 0 to 27027
Data columns (total 69 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ORIGEM        27028 non-null  int64
 1   CODESTAB      26913 non-null  float64
 2   CODMUNNASC    27028 non-null  int64
 3   LOCNASC       27028 non-null  int64
 4   IDADEMAE      27028 non-null  int64
 5   ESTCIVMAE     26711 non-null  float64
 6   ESCMAE        26716 non-null  object
 7   CODOCUPMAE    24121 non-null  float64
 8   QTDFILVIVO    25455 non-null  float64
 9   QTDFILMORT    24930 non-null  float64
 10  CODMUNRES     27028 non-null  int64
 11  GESTACAO      25796 non-null  object
 12  GRAVIDEZ      26949 non-null  object
 13  PARTO         26979 non-null  object
 14  CONSULTAS     27028 non-null  int64
 15  DTNASC        27028 non-null  object
 16  HORANASC      27007 non-null  float64
 17  SEXO          27024 non-null  object
 18  APGAR1        26932 non-null  float64
 19  APGAR5        26925 non-null  float64
 20  RACACOR       26381 non-null  object
 21  PESO          27028 non-null  int64
 22  IDANOMAL      26437 non-null  float64
 23  DTCADASTRO    27028 non-null  object
 24  CODANOMAL     214 non-null    object
 25  NUMEROLOTE    27028 non-null  int64
 26  VERSAOSIST    27028 non-null  object
 27  DTRECEBIM     27028 non-null  object
 28  DIFDATA       27028 non-null  int64
 29  DTRECORIGA    0 non-null      float64
 30  NATURALMAE    26730 non-null  float64
 31  CODMUNNATU    26730 non-null  float64
 32  CODUFNATU     26730 non-null  float64
 33  ESCMAE2010    26779 non-null  float64
 34  SERIESCMAE    14318 non-null  float64
 35  DTNASCMAE     26988 non-null  float64
 36  RACACORMAE    26367 non-null  float64
 37  QTDGESTANT    25816 non-null  float64
 38  QTDPARTNOR    25149 non-null  float64
 39  QTDPARTCES    25237 non-null  float64
 40  IDADEPAI      7607 non-null   float64
 41  DTULTMENST    16956 non-null  float64
 42  SEMAGESTAC    25790 non-null  float64
 43  TPMETESTIM    25790 non-null  float64
 44  CONSPRENAT    26098 non-null  float64
 45  MESPRENAT     24161 non-null  float64
 46  TPAPRESENT    26763 non-null  float64
 47  STTRABPART    26081 non-null  float64
 48  STCESPARTO    26281 non-null  float64
 49  TPNASCASSI    26967 non-null  float64
 50  TPFUNCRESP    26961 non-null  float64
 51  TPDOCRESP     27014 non-null  float64
 52  DTDECLARAC    26976 non-null  float64
 53  ESCMAEAGR1    26779 non-null  float64
 54  STDNEPIDEM    27028 non-null  int64
 55  STDNNOVA      27028 non-null  int64
 56  CODPAISRES    27028 non-null  int64
 57  TPROBSON      27028 non-null  int64
 58  PARIDADE      27028 non-null  int64
 59  KOTELCHUCK    27028 non-null  int64
 60  CONTADOR      27028 non-null  int64
 61  munResStatus  27028 non-null  object
 62  munResTipo    27028 non-null  object
 63  munResNome    27028 non-null  object
 64  munResUf      27028 non-null  object
 65  munResLat     27027 non-null  float64
 66  munResLon     27027 non-null  float64
 67  munResAlt     27027 non-null  float64
 68  munResArea    27027 non-null  float64
dtypes: float64(38), int64(16), object(15)
memory usage: 14.2+ MB

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [102]:
sinasc_1 = sinasc_raw[['IDADEMAE', 'IDADEPAI','munResNome','QTDFILVIVO']]
sinasc_1.head()

   IDADEMAE  IDADEPAI               munResNome  QTDFILVIVO
0        19      26.0    Alta Floresta D'Oeste         0.0
1        29      24.0    Alta Floresta D'Oeste         1.0
2        37      32.0    Alta Floresta D'Oeste         2.0
3        30      24.0  Alto Alegre dos Parecis         0.0
4        30      27.0    Alta Floresta D'Oeste         1.0

In [111]:
resultados = sinasc_1.groupby('munResNome')[['IDADEMAE', 'IDADEPAI', 'QTDFILVIVO']].mean()

resultados_sorted = resultados.sort_values(by='QTDFILVIVO', ascending=False)

resultados_sorted

                            IDADEMAE   IDADEPAI  QTDFILVIVO
munResNome
Guajará-Mirim              25.462228  30.470588    1.543563
Candeias do Jamari         25.243323  29.894737    1.433775
Itapuã do Oeste            26.064220  42.500000    1.410000
Espigão D'Oeste            26.093333  31.198113    1.405830
Buritis                    25.559177  30.812500    1.353846
Parecis                    26.454545  32.473684    1.302326
Nova Mamoré                25.326389  31.692308    1.295455
Costa Marques              24.412017  30.613636    1.258772
Cujubim                    24.482927  31.400000    1.256158
Rio Crespo                 26.660000  28.000000    1.255319
Vale do Anari              26.096774  34.000000    1.173913
Santa Luzia D'Oeste        26.121212  30.703297    1.171717
Porto Velho                26.312670  32.352679    1.167236
Alto Paraíso               24.960177  28.833333    1.162896
Campo Novo de Rondônia     24.825301  30.500000    1.160305
Pimenteiras do Oeste       25.075000  35.600000    1.150000
Machadinho D'Oeste         25.480000  31.326923    1.114286
Ministro Andreazza         27.904762  33.849315    1.095238
Primavera de Rondônia      27.023256  31.888889    1.093023
Chupinguaia                25.333333  29.629630    1.081250
São Francisco do Guaporé   25.660066  31.638889    1.079734
Castanheiras               27.281250  30.392857    1.062500
Cacaulândia                25.546667  36.333333    1.013333
Município ignorado - RO    24.000000  22.000000    1.000000
Monte Negro                25.648241  34.678571    0.989583
Cerejeiras                 27.240506  31.652778    0.987124
Alvorada D'Oeste           25.770732  30.757282    0.975248
Ariquemes                  25.607866  32.466667    0.962253
Urupá                      26.688235  31.008929    0.946746
Colorado do Oeste          27.602804  34.354839    0.934579
Ji-Paraná                  26.361137  31.132239    0.933272
Mirante da Serra           26.304878  32.154762    0.932515
Presidente Médici          25.796053  30.150754    0.930233
Vilhena                    26.433962  34.152941    0.917929
Alto Alegre dos Parecis    24.844156  29.179104    0.907895
Theobroma                  25.536082  30.083333    0.905263
Ouro Preto do Oeste        26.375594  31.233244    0.899361
Cacoal                     26.890102  30.931854    0.899123
Jaru                       25.982974  32.197183    0.891304
São Miguel do Guaporé      25.926346  32.666667    0.891117
Seringueiras               24.910714  30.500000    0.880240
Nova Brasilândia D'Oeste   26.222222  30.520833    0.879845
Pimenta Bueno              25.199675  29.745174    0.863934
Teixeirópolis              26.031250  31.500000    0.859375
Rolim de Moura             26.600863  30.360479    0.858542
Alta Floresta D'Oeste      25.991826  29.548701    0.856354
Corumbiara                 24.716535  32.470588    0.849206
Nova União                 26.894231  31.371429    0.844660
Novo Horizonte do Oeste    26.938776  31.588235    0.835052
São Felipe D'Oeste         26.481481  31.395833    0.773585
Governador Jorge Teixeira  24.401786  29.222222    0.768519
Cabixi                     26.037500  34.333333    0.762500
Vale do Paraíso            25.679012  29.976744    0.696203

In [112]:
resultados = sinasc_1.groupby('munResNome')[['IDADEMAE', 'IDADEPAI', 'QTDFILVIVO']].min()

resultados_sorted = resultados.sort_values(by='QTDFILVIVO', ascending=False)

resultados_sorted

                           IDADEMAE  IDADEPAI  QTDFILVIVO
munResNome
Município ignorado - RO          24      22.0         1.0
Monte Negro                      14      20.0         0.0
Nova Brasilândia D'Oeste         15      20.0         0.0
Nova Mamoré                      14      19.0         0.0
Nova União                       16      18.0         0.0
Novo Horizonte do Oeste          15      20.0         0.0
Ouro Preto do Oeste              14      17.0         0.0
Parecis                          16      18.0         0.0
Pimenta Bueno                    13      16.0         0.0
Pimenteiras do Oeste             14      25.0         0.0
Porto Velho                      12      16.0         0.0
Presidente Médici                14      16.0         0.0
Primavera de Rondônia            16      21.0         0.0
Alta Floresta D'Oeste            14      17.0         0.0
Rolim de Moura                   14      16.0         0.0
Santa Luzia D'Oeste              15      18.0         0.0
Seringueiras                     14      20.0         0.0
São Felipe D'Oeste               17      18.0         0.0
São Francisco do Guaporé         14      19.0         0.0
São Miguel do Guaporé            14      19.0         0.0
Teixeirópolis                    16      20.0         0.0
Theobroma                        15      23.0         0.0
Urupá                            15      17.0         0.0
Vale do Anari                    14      23.0         0.0
Vale do Paraíso                  14      18.0         0.0
Rio Crespo                       16      28.0         0.0
Mirante da Serra                 14      20.0         0.0
Alto Alegre dos Parecis          14      16.0         0.0
Ministro Andreazza               17      21.0         0.0
Alto Paraíso                     11      21.0         0.0
Alvorada D'Oeste                 15      17.0         0.0
Ariquemes                        13      20.0         0.0
Buritis                          14      18.0         0.0
Cabixi                           13      19.0         0.0
Cacaulândia                      16      28.0         0.0
Cacoal                           14      17.0         0.0
Campo Novo de Rondônia           13      21.0         0.0
Candeias do Jamari               14      21.0         0.0
Castanheiras                     17      17.0         0.0
Cerejeiras                       15      19.0         0.0
Chupinguaia                      13      20.0         0.0
Colorado do Oeste                15      23.0         0.0
Corumbiara                       15      21.0         0.0
Costa Marques                    12      17.0         0.0
Cujubim                          14      19.0         0.0
Espigão D'Oeste                  14      16.0         0.0
Governador Jorge Teixeira        13      22.0         0.0
Guajará-Mirim                    13      19.0         0.0
Itapuã do Oeste                  15      25.0         0.0
Jaru                             12      19.0         0.0
Ji-Paraná                        12      15.0         0.0
Machadinho D'Oeste               13      17.0         0.0
Vilhena                          14      18.0         0.0

In [113]:
resultados = sinasc_1.groupby('munResNome')[['IDADEMAE', 'IDADEPAI', 'QTDFILVIVO']].max()

resultados_sorted = resultados.sort_values(by='QTDFILVIVO', ascending=False)

resultados_sorted

                           IDADEMAE  IDADEPAI  QTDFILVIVO
munResNome
Santa Luzia D'Oeste              41      53.0        30.0
Costa Marques                    41      60.0        14.0
Espigão D'Oeste                  44      86.0        12.0
Porto Velho                      47      65.0        12.0
Guajará-Mirim                    43      44.0        11.0
Machadinho D'Oeste               44      53.0        10.0
Vilhena                          46      60.0        10.0
Buritis                          44      49.0        10.0
Pimenta Bueno                    47      70.0         9.0
Alvorada D'Oeste                 44      52.0         9.0
Nova Mamoré                      46      43.0         8.0
Cerejeiras                       53      52.0         8.0
Chupinguaia                      42      46.0         8.0
Colorado do Oeste                47      53.0         8.0
Ariquemes                        44      51.0         8.0
Vale do Anari                    44      58.0         8.0
Ji-Paraná                        44      63.0         8.0
Candeias do Jamari               45      41.0         8.0
Presidente Médici                44      64.0         7.0
Jaru                             45      62.0         7.0
Monte Negro                      40      55.0         7.0
Alta Floresta D'Oeste            53      58.0         7.0
Cacoal                           47      66.0         7.0
Cujubim                          42      44.0         7.0
Cacaulândia                      42      50.0         7.0
Ouro Preto do Oeste              44      60.0         6.0
Alto Paraíso                     42      49.0         6.0
Teixeirópolis                    39      67.0         6.0
São Miguel do Guaporé            42      60.0         6.0
São Francisco do Guaporé         41      54.0         6.0
Itapuã do Oeste                  46      73.0         6.0
Castanheiras                     39      43.0         6.0
Ministro Andreazza               44      55.0         6.0
Mirante da Serra                 46      56.0         5.0
Parecis                          41      61.0         5.0
Campo Novo de Rondônia           40      40.0         5.0
Pimenteiras do Oeste             40      45.0         5.0
Governador Jorge Teixeira        41      37.0         5.0
Urupá                            43      48.0         5.0
Rolim de Moura                   44      69.0         5.0
Seringueiras                     42      47.0         5.0
São Felipe D'Oeste               41      57.0         5.0
Alto Alegre dos Parecis          41      50.0         5.0
Corumbiara                       43      52.0         4.0
Vale do Paraíso                  52      51.0         4.0
Theobroma                        42      45.0         4.0
Nova União                       39      53.0         4.0
Novo Horizonte do Oeste          41      56.0         4.0
Rio Crespo                       39      28.0         4.0
Primavera de Rondônia            39      44.0         4.0
Nova Brasilândia D'Oeste         51      48.0         4.0
Cabixi                           39      47.0         4.0
Município ignorado - RO          24      22.0         1.0

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [114]:
sinasc_2 = sinasc_raw[['PESO', 'DTNASC', 'ESCMAE']]
sinasc_2.head(15)

    PESO     DTNASC           ESCMAE
0   3685 2019-02-19      8 a 11 anos
1   3055 2019-02-21      8 a 11 anos
2   3460 2019-02-25      8 a 11 anos
3   2982 2019-03-20  12 anos ou mais
4   3310 2019-03-23      8 a 11 anos
5   2740 2019-03-27       1 a 3 anos
6   3158 2019-04-01      8 a 11 anos
7   3192 2019-04-01  12 anos ou mais
8   3570 2019-02-28      8 a 11 anos
9   3900 2019-03-11       1 a 3 anos
10  3590 2019-03-11      8 a 11 anos
11  3510 2019-03-12       4 a 7 anos
12  2950 2019-03-18      8 a 11 anos
13  2995 2019-03-28       1 a 3 anos
14  2550 2019-03-11       4 a 7 anos

In [58]:

sinasc_raw['DTNASC'] = pd.to_datetime(sinasc_raw['DTNASC'])

sinasc_raw_filtrado = sinasc_raw[sinasc_raw['DTNASC'] == '2019-03-27']
peso_medio = sinasc_raw_filtrado.groupby(['ESCMAE', 'SEXO'])['PESO'].mean()

peso_medio.to_frame()

                                  PESO
ESCMAE          SEXO
1 a 3 anos      Feminino   3650.000000
                Masculino  2845.000000
12 anos ou mais Feminino   3462.142857
                Masculino  3356.666667
4 a 7 anos      Feminino   3261.818182
                Masculino  3512.500000
8 a 11 anos     Feminino   3275.888889
                Masculino  3215.190476

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [117]:

sinasc_raw['DTNASC'] = pd.to_datetime(sinasc_raw['DTNASC'])

nascimentos_por_municipio = sinasc_raw['munResNome'].value_counts()

municipio_menos_nascimentos = nascimentos_por_municipio.idxmin()
nascimentos_municipio_menos = nascimentos_por_municipio.min()

print(f'O município com menos nascimentos em 2019 foi {municipio_menos_nascimentos} com {nascimentos_municipio_menos} nascimentos.')

O município com menos nascimentos em 2019 foi Município ignorado - RO com 1 nascimentos.

In [76]:
municipio_stats = sinasc_raw.groupby('munResNome')[['IDADEMAE', 'IDADEPAI']].agg(
    idade_media_mae=('IDADEMAE', 'mean'),
    idade_maxima_mae=('IDADEMAE', 'max'),
    idade_minima_mae=('IDADEMAE', 'min'),
    idade_media_pai=('IDADEPAI', 'mean'),
    idade_maxima_pai=('IDADEPAI', 'max'),
    idade_minima_pai=('IDADEPAI', 'min')
)
municipio_stats.loc[municipio_menos_nascimentos].to_frame()

                  Município ignorado - RO
idade_media_mae                      24.0
idade_maxima_mae                     24.0
idade_minima_mae                     24.0
idade_media_pai                      22.0
idade_maxima_pai                     22.0
idade_minima_pai                     22.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [97]:
# Filtrar os nascimentos que ocorreram no mês de março
sinasc_marco = sinasc_raw[sinasc_2019['DTNASC'].dt.month == 3]
sinasc_marco

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
5,1,2516500.0,110001,1,33,5.0,1 a 3 anos,621005.0,2.0,1.0,...,5,6,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
9,1,2679477.0,110001,1,30,2.0,1 a 3 anos,999992.0,1.0,1.0,...,5,10,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
10,1,2679477.0,110001,1,31,5.0,8 a 11 anos,512105.0,1.0,0.0,...,5,11,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13670,1,2000733.0,120040,1,24,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,18687,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13671,1,2000733.0,120040,1,24,5.0,4 a 7 anos,999992.0,2.0,0.0,...,9,18702,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13736,1,2688611.0,355030,1,35,2.0,12 anos ou mais,10210.0,1.0,0.0,...,5,1066018,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13748,1,2311682.0,510340,1,36,4.0,12 anos ou mais,354605.0,2.0,1.0,...,5,1386627,ATIVO,MUNIC,Vilhena,Rondônia,-12.74137,-60.13858,595.0,11518.915
13750,1,2604388.0,510340,1,31,2.0,12 anos ou mais,142305.0,0.0,1.0,...,5,1388221,ATIVO,MUNIC,Ji-Paraná,Rondônia,-10.88205,-61.94509,157.0,6896.648

In [98]:

municipio_nascimentos_marco = sinasc_marco['munResNome'].value_counts()

municipio_mais_nascimentos = municipio_nascimentos_marco.idxmax()
nascimentos_municipio_mais = municipio_nascimentos_marco.max()

print(f"Município com mais nascimentos em março: {municipio_mais_nascimentos}")
print(f"Número de nascimentos: {nascimentos_municipio_mais}")

Município com mais nascimentos em março: Porto Velho
Número de nascimentos: 744

In [99]:

municipio_stats_marco = sinasc_marco[sinasc_marco['munResNome'] == municipio_mais_nascimentos]

municipio_stats1 = municipio_stats_marco[['QTDFILVIVO', 'IDADEPAI', 'IDADEMAE']].agg(
    filhos_vivos_media=('QTDFILVIVO', 'mean'),
    filhos_vivos_maxima=('QTDFILVIVO', 'max'),
    filhos_vivos_minima=('QTDFILVIVO', 'min'),
    idade_media_pai=('IDADEPAI', 'mean'),
    idade_maxima_pai=('IDADEPAI', 'max'),
    idade_minima_pai=('IDADEPAI', 'min'),
     idade_media_mae=('IDADEMAE', 'mean'),
    idade_maxima_mae=('IDADEMAE', 'max'),
    idade_minima_mae=('IDADEMAE', 'min')
)

municipio_stats1

                     QTDFILVIVO   IDADEPAI   IDADEMAE
filhos_vivos_media     1.295056        NaN        NaN
filhos_vivos_maxima    9.000000        NaN        NaN
filhos_vivos_minima    0.000000        NaN        NaN
idade_media_pai             NaN  34.629032        NaN
idade_maxima_pai            NaN  62.000000        NaN
idade_minima_pai            NaN  19.000000        NaN
idade_media_mae             NaN        NaN  26.596774
idade_maxima_mae            NaN        NaN  44.000000
idade_minima_mae            NaN        NaN  14.000000

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

**Conclusão**

Podemos identificar que a capital do Estado de Rondônio foi onde aconteceu o maior numero de nascimentos no mês de março. E que seria necessário ser investido em um programa de educação sexual, por mais que a idade média das mães seja alta existem mães muito novas.

In [6]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [7]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [8]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')